# fly.toml app configuration file generated for plate-example on 2024-12-13T15:29:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plate-example'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
